apiVersion: v1
kind: Service
metadata:
  name: hit-counter-api
  labels:
    app: hit-counter-api
spec:
  type: NodePort
  selector:
    app: hit-counter-api
  ports:
  - port: 80
    targetPort: 5000
    nodePort: 30000
    name: http